steps:

  - id: 'Instalando'
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'sum']
    env: ['GOPATH=.']

  - id: "Montando imagem Docker"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio_ci:latest", "."]

  - id: "teste"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: ['-c', 'ls .']

  - id: "Compilando Golang"
    name: "gcr.io/cloud-builders/go"
    args: ["run", "sum"]
    env: ["GOPATH=."]

images:
  - 'gcr.io/$PROJECT_ID/desafio_ci:latest'